services:
  djangoapp:
    container_name: djangoapp
    build:
      context: . #indica que vai usar o arquivo dockerfile na raiz do projeto
    ports:
      - 8000:8000 #redireciona a porta 8000 do computador para a 8000 da imagem
    volumes: #mapei os volumens
    #aqui o nome da pasta deve ser igual ao nome do conteiner e nome do projeto Django
      - ./djangoapp:/djangoapp #sincroniza a pasta com a pasta do conteiner
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:16.2-alpine3.19
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env